### ISSUE TITLE
error when running requirements.txt

### ISSUE THREAD

**Issue by leohoy** [GeoNode/geonode-project#105]
I am following this tutorial http://docs.geonode.org/en/2.10.x/install/project/index.html#geonode-project-installation

I get an error when I paste this with sudo: `pip install -r requirements.txt --upgrade --no-cache --no-cache-dir`

> ERROR: my-geonode 2.10.1 has requirement celery==4.4.0, but you'll have celery 4.2.1 which is incompatible.
ERROR: my-geonode 2.10.1 has requirement coverage==5.0.1, but you'll have coverage 4.5.4 which is incompatible.
ERROR: my-geonode 2.10.1 has requirement django-leaflet==0.26.0, but you'll have django-leaflet 0.25.0 which is incompatible.
ERROR: my-geonode 2.10.1 has requirement geonode-dialogos==3.0, but you'll have geonode-dialogos 1.2 which is incompatible.
ERROR: my-geonode 2.10.1 has requirement kombu==4.6.7, but you'll have kombu 4.6.6 which is incompatible.
ERROR: my-geonode 2.10.1 has requirement lxml==4.4.2, but you'll have lxml 4.4.1 which is incompatible.
ERROR: my-geonode 2.10.1 has requirement psutil==5.6.7, but you'll have psutil 5.6.5 which is incompatible.
ERROR: my-geonode 2.10.1 has requirement pytest==4.6.8, but you'll have pytest 4.6.6 which is incompatible.
ERROR: my-geonode 2.10.1 has requirement setuptools==42.0.2, but you'll have setuptools 42.0.0 which is incompatible.
ERROR: my-geonode 2.10.1 has requirement splinter==0.13.0, but you'll have splinter 0.11.0 which is incompatible.
ERROR: my-geonode 2.10.1 has requirement tqdm==4.40.2, but you'll have tqdm 4.39.0 which is incompatible.
Installing collected packages: lxml, psycopg2, pyyaml, Paver, billiard, kombu, celery, boto, tqdm, django-jsonfield, django-leaflet, geonode-user-messages, geonode-agon-ratings, geonode-dialogos, python-memcached, psutil, coverage, poster, pytest, splinter, setuptools, GeoNode
  Found existing installation: lxml 4.4.2
    Uninstalling lxml-4.4.2:
      Successfully uninstalled lxml-4.4.2
  Found existing installation: psycopg2 2.7.4
ERROR: Cannot uninstall 'psycopg2'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

**Comment by t-book** [comment]
It looks you somehow mixed up branches. In case you like to install geonode-project branch 2.10.1 geonode core 2.10.1 will be installed. https://github.com/GeoNode/geonode-project/blob/2.10.1/requirements.txt#L4 this installs f.e. celery 4.2.1 https://github.com/GeoNode/geonode/blob/2.10.1/requirements.txt#L19

However. In case geonode-core master branch  branch is installed it will end with celery 4.4.0 https://github.com/GeoNode/geonode/blob/master/requirements.txt#L19 long story short maybe recreate your virtualenv and double-check the requirements.

**Comment by leohoy** [comment]
so how would I edit my requirements.txt in this case? right now I have it in the default: 
```

# GeoNode
# from Pypi:
#GeoNode==2.10.2
-e git+https://github.com/GeoNode/geonode.git@2.10.x#egg=GeoNode
```

**Comment by t-book** [comment]
ok this looks fine. Let me test it to be sure nothing is wrong with geonode-project <> geonode core

**Comment by t-book** [comment]
@leohoy just tested. The setup worked for me. This is what I did. Can you test it?

```
  515  cd /tmp
  516  mkdir env
  517  virtualenv env --python=/usr/bin/python2.7
  518  source env/bin/activate
  519  git clone https://github.com/GeoNode/geonode-project.git -b 2.10.x
  520  pip install Django==1.11.25
  521  django-admin startproject --template=./geonode-project -e py,sh,md,rst,json,yml,ini,env,sample -n monitoring-cron -n Dockerfile my_geonode
  522  cd my_geonode
  523  pip install -r requirements.txt --upgrade
  524  pip install -e . --upgrade
  525  pip install pygdal=="`gdal-config --version`.*"
  526  DJANGO_SETTINGS_MODULE=my_geonode.settings paver setup
  527  DJANGO_SETTINGS_MODULE=my_geonode.settings paver sync
  528  DJANGO_SETTINGS_MODULE=my_geonode.settings paver start
```

**Comment by t-book** [comment]
( after that you should see geonode at localhost:8000 )

**Comment by leohoy** [comment]
worked! The difference was that before I wasnt able to use the commands without sudo... now with deploying it in the tmp directory, it worked perfectly.

**Comment by t-book** [comment]
@leohoy great to hear. But /tmp is  not the right place for installation ;) (Just used it for a quick test, some systems delete it on boot!) You should check the permissions of your users and the path where you trying to install.
