### ISSUE TITLE
Run geonode-project on ubuntu 18.04

### ISSUE THREAD

**Issue by antt** [GeoNode/geonode-project#117]
I have error /usr/bin/geonode: line 14: django-admin.py: command not found when run sudo PYTHONWARNINGS=ignore VIRTUAL_ENV=$VIRTUAL_ENV DJANGO_SETTINGS_MODULE=my_geonode.local_settings GEONODE_ETC=/opt/geonode_custom/my_geonode GEOSERVER_DATA_DIR=/opt/data/geoserver_data TOMCAT_SERVICE="service tomcat" APACHE_SERVICE="service nginx" geonode_updateip -p xxx

**Comment by frafra** [comment]
It looks like Django is not installed, or it is not available system-wide.

**Comment by t-book** [comment]
... or you forgot to copy the command `sudo cp package/support/geonode.updateip /usr/bin/geonode_updateip` ?

**Comment by frafra** [comment]
Oh, yes, that is it. I was confused by the fact that it is not clear what is a descriptive text from the user and what is the actual error :)

**Comment by antt** [comment]
I made copy file geonode.updateip anh geonode to /urs/bin
