### ISSUE TITLE
site_index.html is not working

### ISSUE THREAD

**Issue by MoRadwan74** [GeoNode/geonode-project#125]
I've installed GeoNode project 2.10.x using with [GeoNode project installation guide][1]. And walk through the [GeoNode theming, Templates, and Static files][2].

Knowing that `site_index.html` is the template used to define GeoNode project’s homepage, I tried to edit it with the example provided in the docs with no luck of overriding the available code at the GeoNode's `index.html`.

Is there anything to be checked?

[1]: https://docs.geonode.org/en/master/install/project/index.html#geonode-project-installation
[2]: https://docs.geonode.org/en/2.10/basic/theme/index.html#templates-and-static-pages

**Comment by ddovnar** [comment]
I have similar problem. There is a urls.py module doesn't load, that's why changes are not apply in the index.html

**Comment by MoRadwan74** [comment]
@ddovnar what module?

**Comment by ddovnar** [comment]
your_project/urls.py. In this module, loading project site_index.html template, but if we comment all module contents, app still working. Because app using core urls.py module

**Comment by MoRadwan74** [comment]
Anyway, It should use both urls.py modules(core and project) but you're right. I think the issue is at this file, can't figure it out though.

**Comment by t-book** [comment]
Stupid question but have you respected Django tags in your changes? like {% block hero %} ...
URLs are overridden here: https://github.com/GeoNode/geonode-project/blob/master/project_name/settings.py#L62 this is where I would start in other words which settings are in use and which file succeeds on setting variables.

**Comment by MoRadwan74** [comment]
Solved!! .. I'm using local_settings.py so when I added these lines to it, it worked and now my `site_index.html` is working. I thought `local_settings.py` inherits from 'settings.py' so I don't need to add the URL mapping part.

Anyway, thank you @t-book, and please accept this silly mistake.

**Comment by t-book** [comment]
you're welcome @MoRadwan74
