### ISSUE TITLE
Could not get the result of WFS request

### ISSUE THREAD

**Issue by iamtekson** [GeoNode/geonode-project#134]
I uploaded some required data into GeoNode. Now I can fetch the data using GeoServer WMS request. But when I tried to get the data using WFS request, it shows the following error,

```
<ows:ExceptionReport xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ows="http://www.opengis.net/ows" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0.0" xsi:schemaLocation="http://www.opengis.net/ows https://master.demo.geonode.org/geoserver/schemas/ows/1.0.0/owsExceptionReport.xsd?access_token=ZXKRZlrPDpkEcPs90Gt6isGv1vT1HM">
<ows:Exception exceptionCode="InvalidParameterValue" locator="outputFormat">
<ows:ExceptionText>
Failed to find response for output format text/javascript
</ows:ExceptionText>
</ows:Exception>
</ows:ExceptionReport>
```

I think this error arise due to not enabling the `jsonp` in GeoServer. I know it can be enabled by uncommenting following line of code in `/tomcat/webapps/geoserver/WEB-INF/web.xml` file,

```xml
<context-param>
    <param-name>ENABLE_JSONP</param-name>
    <param-value>true</param-value>
</context-param>
```

**Comment by t-book** [comment]
@iamtekson thanks for sharing! Is there something that needs to be considered? Otherwise, we could close here.

**Comment by iamtekson** [comment]
Can you enable the `jsonp` format for [http://master.demo.geonode.org/](http://master.demo.geonode.org/) site? Actually I want to host some of my shapefile in this site and get the WFS data in `leaflet`. 

```
$.ajax("https://master.demo.geonode.org/geoserver/wfs", {
    type: "GET",
    data: {
      service: "WFS",
      version: "1.1.0",
      request: "GetFeature",
      typename: "geonode:nepal3",
      srsname: "EPSG:4326",
      outputFormat: "text/javascript",
    },
    dataType: "jsonp",
    jsonpCallback: "callback:handleJson",
    jsonp: "format_options",
  });


// the ajax callback function
function handleJson(data) {
  selectedArea = L.geoJson(data, {
    style: geoJsonStyle,
  }).addTo(map);
  map.fitBounds(selectedArea.getBounds());
```
I think it is still not enabled.

**Comment by t-book** [comment]
@iamtekson the master instance is not under my responsibility, so unfortunately I cannot help here. However, I would not suggest at all to host productive files on the test instance as it could be reset and recreated every time ;) It's purpose is to show what geonode can do.

**Comment by iamtekson** [comment]
Ok, I understand the situation. I already installed the GeoNode in my machine and hosted there. Thank you for the response. Now better to close this issue.
