### ISSUE TITLE
Docker installation question

### ISSUE THREAD

**Issue by tsega** [GeoNode/geonode-project#137]
Is the [docker installation instruction](https://github.com/GeoNode/geonode-project#start-your-server-using-docker) in the project README correct? It has the exact same instructions as setting the project up with [Python Virtual Environment](https://github.com/GeoNode/geonode-project#using-a-python-virtual-environment). 

I believe the following lines need to be removed from the **Prepare the environment** section of Docker based instructions:
```
source /usr/share/virtualenvwrapper/virtualenvwrapper.sh
mkvirtualenv --python=/usr/bin/python3 {{ project_name }}
pip install Django==2.2.12

django-admin startproject --template=./geonode-project -e py,sh,md,rst,json,yml,ini,env,sample,properties -n monitoring-cron -n Dockerfile {{ project_name }}
```

**Comment by fpennica** [comment]
When choosing a docker installation you still need a Django environment to generate (with `django-admin startproject`) the new project based on the geonode-project template, that's what the virtualenv is for, if I understand correctly.

**Comment by afabiani** [comment]
Correct

**Comment by t-book** [comment]
🎯

**Comment by t-book** [comment]
@tsega It looks this is clear now. I'm closing here. Please reopen if needed.
