### ISSUE TITLE
geonode-project 3.0 site_index template error

### ISSUE THREAD

**Issue by fpennica** [GeoNode/geonode-project#138]
Hello, this seems too much an obvious issue, so I must be doing something terribly wrong...

This is what I do:

```bash
# to be sure the system is clean
docker system prune -a --volumes

# clone the 3.0 branch
git clone https://github.com/GeoNode/geonode-project.git -b 3.0

# create new project
mkvirtualenv --python=/usr/bin/python3 igag_geonode
pip3 install Django==2.2.12
django-admin startproject --template=./geonode-project -e py,sh,md,rst,json,yml,ini,env,sample -n monitoring-cron -n Dockerfile igag_geonode

# startup project
cd igag_geonode
docker-compose build --no-cache
docker-compose up -d
```

Opening `localhost` in the browser I get:

![Screenshot-20200617101223-969x367](https://user-images.githubusercontent.com/14745333/84873212-32572e00-b083-11ea-89da-eb6e9b325602.png)

Setting `DEBUG=True` in `.env`:

![Screenshot-20200617100225-1025x736](https://user-images.githubusercontent.com/14745333/84873346-63376300-b083-11ea-8938-eadfc49772ed.png)

If I remove every `|template_trans` from `site_index.html` and start up docker-compose with:

```bash
docker-compose -f docker-compose.yml -f docker-compose.override.yml up -d
```

to mount the local modified templates, the problem is solved.

Is there something wrong I'm doing? Is the 3.0 brach intended to have a "stable" 3.0 geonode project?

Thanks.

**Comment by afabiani** [comment]
@fpennica you are right, "template_trans" template tag is available on 3.x only.

Will remove it.

**Comment by fpennica** [comment]
Ok, thanks, there is still a `template_trans` in line 10: https://github.com/GeoNode/geonode-project/blob/ed157dbe16c409b2202ebc3ab91c96906bc2acc8/project_name/templates/site_index.html#L10

**Comment by afabiani** [comment]
I removed it too, thanks!

**Comment by t-book** [comment]
@fpennica did this solve your issue? Can we close here?

**Comment by fpennica** [comment]
Yes, this is solved now!

**Comment by t-book** [comment]
thanks @fpennica
