### ISSUE TITLE
is there a way to debug letsencrypt

### ISSUE THREAD

**Issue by d3netxer** [GeoNode/geonode-project#143]
I was able to install GeoNode 3 using the online instructions. I am able to set up my site using my own custom domain. I have changed the domain to use https and in my .env file I have used the 'LETSENCRYPT_MODE=staging' setting. This is working well for me, I only have to bypass the warning in my browser to reach the site.

However, I have tried changing the setting to 'LETSENCRYPT_MODE=production' and I have restarted the services with 'docker compose up -d'.  Now when I try to enter the site on my browser I get this: 

502 Bad Gateway
nginx/1.17.2

Any advice on how to debug this and get letsencrypt to work for me?

Is there some way I can access any logs? Such as the print statements from this file: https://github.com/GeoNode/geonode-project/blob/master/docker/letsencrypt/docker-entrypoint.sh

or how could I access where the certs are being saved?

Thanks

**Comment by d3netxer** [comment]
I am able to view the logs with the following command: 'docker logs mygeonode_letsencrypt_1'

it outputs the following:

-----------------------------------------------------
STARTING LETSENCRYPT ENTRYPOINT ---------------------
Tue Jun 30 23:20:50 UTC 2020

Trying to get PRODUCTION certificate
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator webroot, Installer None
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for mydomain.com
Using the webroot path /geonode-certificates for all unmatched domains.
Waiting for verification...
Cleaning up challenges
Non-standard path(s), might not work with crontab installed by your operating system package manager
IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at:
   /geonode-certificates/production/live/mydomain.com/fullchain.pem
   Your key file has been saved at:
   /geonode-certificates/production/live/mydomain.com/privkey.pem
   Your cert will expire on 2020-09-28. To obtain a new or tweaked
   version of this certificate in the future, simply run certbot
   again. To non-interactively renew *all* of your certificates, run
   "certbot renew"
 - Your account credentials have been saved in your Certbot
   configuration directory at /geonode-certificates/production. You
   should make a secure backup of this folder now. This configuration
   directory will also contain certificates and private keys obtained
   by Certbot so making regular backups of this folder is ideal.
 - If you like Certbot, please consider supporting our work by:

   Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
   Donating to EFF:                    https://eff.org/donate-le


Certificate have been created/renewed successfully
-----------------------------------------------------
FINISHED LETSENCRYPT ENTRYPOINT ---------------------
-----------------------------------------------------


This seems to look good to me, it seems like the certificate has been issued successfully. Where is the '/geonode-certificates' directory? Is that within the container?

Most importantly the https certificate is working now for the site. I think most likely because for Let's Encrypt certificates the issuance is generally between 30 minutes and 1 hour.

I will close this issue.

**Comment by t-book** [comment]
>  Is that within the container?

correct. and volumed to keep it persistent
