### ISSUE TITLE
docker-compose build is failing due to proj tests

### ISSUE THREAD

**Issue by t-book** [GeoNode/geonode-project#157]
`docker-compose build --no-cache` is currently failing for me with following error:

<img width="1305" alt="Bildschirmfoto 2020-10-18 um 18 47 29" src="https://user-images.githubusercontent.com/20478652/96375084-369d7000-1177-11eb-8f09-44820fdba327.png">

This as one of the tests is failing when the deb package is building proj:
https://hastebin.com/fiboxetugo.log

Until now I have no idea what changed but for a quick fix one could disable tests to make the build work again. (which obviously is not the best solution)

`RUN cd /tmp/proj &&` **DEB_BUILD_OPTIONS=nocheck**  `debuild -i -us -uc -b && dpkg -i ../*.deb`
https://github.com/GeoNode/geonode-project/blob/master/Dockerfile#L43

can you reproduce this and what do you think @afabiani @gannebamm  ?

**Comment by afabiani** [comment]
@t-book unless you have a arm-64 based host, you can safely comment those lines on the Dockerfile

```
RUN git clone https://salsa.debian.org/debian-gis-team/proj.git /tmp/proj
RUN cd /tmp/proj && debuild -i -us -uc -b && dpkg -i ../*.deb
```

**Comment by t-book** [comment]
thanks @afabiani this makes sense. I wonder if we should make this a bit more failsafe. Untested but to show what I mean:

`RUN if [[ $(uname -a) == *arm* ]] && [[ $(getconf LONG_BIT) == 64 ]]; then cd /tmp/proj && debuild -i -us -uc -b && dpkg -i ../*.deb; fi`

Or leave a big warning @ README ?

**Comment by afabiani** [comment]
@t-book the if looks good, let me test it maybe (unless you already done it)

**Comment by t-book** [comment]
@afabiani thanks unfortunately I currently do not have an arm processor available for testing. Would be great if you can jump in.

**Comment by afabiani** [comment]
@t-book we can probably remove this from master branch and leave it only on **master-arm64** "https://github.com/GeoNode/geonode-project/tree/master-arm64" one

**Comment by t-book** [comment]
@afabiani This sounds good to me +1

**Comment by afabiani** [comment]
Done
