### ISSUE TITLE
https://build.geo-solutions.it/geonode/geoserver/latest/geoserver-2.17.2.war Not Available

### ISSUE THREAD

**Issue by st-rom** [GeoNode/geonode-project#160]
I've made some changes in minor .env file and after rebuilding project website stopped working `502 Bad Gateway`. When I tried to rebuild the project I confronted the problem with https://build.geo-solutions.it/geonode/geoserver/latest/geoserver-2.17.2.war being not available. My guess is that this is what caused an error but I'm not sure. Broken link is called from here https://github.com/GeoNode/geonode-project/blob/master/docker/geoserver/Dockerfile#L14

Error message
`--2020-10-27 13:24:41--  (try: 7)  https://build.geo-solutions.it/geonode/geoserver/latest/geoserver-2.17.2.war
Connecting to build.geo-solutions.it (build.geo-solutions.it)|164.132.91.196|:443... failed: Connection timed out.
Retrying.
`

**Comment by evincentoieau** [comment]
My install is blocked too at the same point, https://build.geo-solutions.it/ is down. I think we have to wait to be up again.

**Comment by gannebamm** [comment]
See also: https://github.com/GeoNode/geonode/issues/6587

The build server is currently down. The responsibles are already informed.

**Comment by afabiani** [comment]
You can temporarily use dropbox, see the needed changes

 - GeoNode [here](https://github.com/GeoNode/geonode/commit/7b970f847dceb33eb0ba562e15330d85648a47d4)

 - GeoNode Project [here](https://github.com/GeoNode/geonode-project/commit/19192302a0a8ed9adc2eb6b2a33bfbbbf12ee333)

**Comment by evincentoieau** [comment]
It's up now
