### ISSUE TITLE
3.X branch fails to build

### ISSUE THREAD

**Issue by t-book** [GeoNode/geonode-project#161]
In preparation for 3.1 release following error occurs on 3.X branch docker:

db4my_geonode    | 2020-11-06 16:48:42.672 UTC [124] ERROR:  permission denied to create extension "postgis"
db4my_geonode    | 2020-11-06 16:48:42.672 UTC [124] HINT:  Must be superuser to create this extension.
db4my_geonode    | 2020-11-06 16:48:42.672 UTC [124] STATEMENT:  CREATE EXTENSION IF NOT EXISTS postgis

**Comment by t-book** [comment]
https://github.com/GeoNode/postgis-docker/blob/master/initdb-geonode.sh#L38

**Comment by afabiani** [comment]
@t-book try to put those vars into .env

POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres

**Comment by t-book** [comment]
Good shot @afabiani but unfortunately those vars are already present in 3.x https://github.com/GeoNode/geonode-project/blob/3.x/.env#L42-L43

**Comment by afabiani** [comment]
uhm, strange. We might revert to postgis:10 in the worst case

but let me take a look.

**Comment by t-book** [comment]
… and set as config shows:

```
tonischonbuchner@Tonis-MBP my_geonode % docker-compose config | grep POSTGRES_USER 
      POSTGRES_USER: postgres
      POSTGRES_USER: postgres
      POSTGRES_USER: postgres
      POSTGRES_USER: postgres
      POSTGRES_USER: postgres
      POSTGRES_USER: postgres
```
anyway … will check where it fails …

**Comment by t-book** [comment]
> uhm, strange. We might revert to postgis:10 in the worst case

Yep that's what I thought as well :/

**Comment by t-book** [comment]
I've just delete all old volumes to be sure nothing comes from there …

**Comment by t-book** [comment]
requirements accidentally pulled from master. 3.x core is working.

Error for master remains. But I will do more testing and open a separate issue for it.
