### ISSUE TITLE
Failed to build with a genode-project called geonode

### ISSUE THREAD

**Issue by vijdz** [GeoNode/geonode-project#168]
` Linux 5.8.0-44-generic #50~20.04.1-Ubuntu SMP / Intel(R) Xeon(R) E-2236 / Docker  20.10.4 build d3cb89e`  
 First time with a fresh django template from 3.x (several .env edit tests with failure / `MEMCACHED_ENABLED=False` also), the clone was from commit https://github.com/GeoNode/geonode-project/commit/73aaf9456cf177a13f747165f3effa41c7168e93 .

Latest test with alignment @ https://github.com/GeoNode/geonode-project/commit/4fa10b57980e04bd398b7e4fba9706d241412326  + bump to python/3.8.8-buster

No changes to .env, I've just edited the override.yml in order to add a ".env.secret", but with default values taken from .env.
[Here is my env](https://github.com/GeoNode/geonode-project/files/6078982/docker-compose_config_output_spec2.2.txt) (`docker-compose config` output).
Steps to reproduce : build && compose up on localhost (default .env production).
The error manifestation has changed a bit since first time but the entrypoint is still looping on error code 1...
It looks like this :
```
django4geonode   | waitfordbs task done
django4geonode   | running migrations
celery4geonode   | waitfordbs task done
celery4geonode   | running migrations
django4geonode exited with code 1
celery4geonode exited with code 1
django4geonode   | Stopping periodic command scheduler: cron.
celery4geonode   | .
celery4geonode   | Starting periodic command scheduler: cron.
django4geonode   | Starting periodic command scheduler: cron.
celery4geonode   | Restarting memcached: start-stop-daemon: warning: failed to kill 38: No such process
django4geonode   | Restarting memcached: start-stop-daemon: warning: failed to kill 38: No such process
django4geonode   | memcached.
celery4geonode   | memcached.
celery4geonode   | \n\n\n
celery4geonode   | -----------------------------------------------------
django4geonode   | \n\n\n
django4geonode   | -----------------------------------------------------
celery4geonode   | STARTING DJANGO ENTRYPOINT Wed Mar  3 19:43:32 UTC 2021
django4geonode   | STARTING DJANGO ENTRYPOINT Wed Mar  3 19:43:32 UTC 2021
celery4geonode   | -----------------------------------------------------
django4geonode   | -----------------------------------------------------
celery4geonode   | DOCKER_API_VERSION="1.24"
celery4geonode   | POSTGRES_USER=postgres
celery4geonode   | POSTGRES_PASSWORD=postgres
celery4geonode   | DATABASE_URL=postgres://geonode:geonode@db:5432/geonode
celery4geonode   | GEODATABASE_URL=postgis://geonode_data:geonode@db:5432/geonode_data
celery4geonode   | SITEURL=http://localhost/
celery4geonode   | ALLOWED_HOSTS=['django', 'localhost', 'localhost:None', 'geonode', 'django']
celery4geonode   | GEOSERVER_PUBLIC_LOCATION=http://localhost/geoserver/
celery4geonode   | MONITORING_ENABLED=True
celery4geonode   | MONITORING_HOST_NAME=geonode
celery4geonode   | MONITORING_SERVICE_NAME=local-geonode
celery4geonode   | MONITORING_DATA_TTL=365
django4geonode   | DOCKER_API_VERSION="1.24"
django4geonode   | POSTGRES_USER=postgres
django4geonode   | POSTGRES_PASSWORD=postgres
django4geonode   | DATABASE_URL=postgres://geonode:geonode@db:5432/geonode
django4geonode   | GEODATABASE_URL=postgis://geonode_data:geonode@db:5432/geonode_data
django4geonode   | SITEURL=http://localhost/
django4geonode   | ALLOWED_HOSTS=['django', 'localhost', 'localhost:None', 'geonode', 'django']
django4geonode   | GEOSERVER_PUBLIC_LOCATION=http://localhost/geoserver/
django4geonode   | MONITORING_ENABLED=True
django4geonode   | MONITORING_HOST_NAME=geonode
django4geonode   | MONITORING_SERVICE_NAME=local-geonode
django4geonode   | MONITORING_DATA_TTL=365
celery4geonode   | waitfordbs task done
celery4geonode   | running migrations
django4geonode   | waitfordbs task done
django4geonode   | running migrations
celery4geonode exited with code 1
django4geonode exited with code 1
```
So it's still going through entrypoint.sh , even with the exit code 1 for the first 2 commands...  
 `service && service && entrypoint.sh` seems to confuse Docker (at least docker-compose is seeing a failed composition, even if everything is probably OK).

I was able to retrieve the source of the exit code 1 (with manual `run -it django4geonode`) because the entrypoint was a also a failure back then. It does not occurs with commit 3.8.8 (memcached version ?).
```python
File "/usr/local/lib/python3.8/site-packages/docker/transport/unixconn.py", line 43, in connect
    sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory
``` 
I can't retrieve the rest of the stack right now, but it's the same cause : `FileNotFoundError` for every function. Python failed to access the socket / pid to `restart`.
From gitter
> Do we really need to restart services before the entrypoint script ? In theory the service is down, so no reason to restart it... Moreover, I believe the entrypoint should be a single file or command !
My guess : our host is running the first 2 commands of the entrypoint in a "transition stage" when container is up : it tries to access a socket inside the container while it's not reachable (yet). May be a recent change in Docker or something ?
I wonder, why not move those two commands (service restart) in the entrypoint.sh file ? If we really need to restart ?

Since @afabiani & @t-book were not able to reproduce my error, it can't be python / memcached version. 
I'm the first and only one to see this, so it's probably related to a recent change in Docker's low-level kernel blackmagic AND/OR local ubuntu config / hardware... Kernel version may be ?

I saw @afabiani took my suggestion into account with https://github.com/GeoNode/geonode-project/commit/7311cb531fa1ded34c63a0cf9a72a4d0611673dc , I will test it (probably not tonight, I had a long day !) but it may be the right fix.

A quick-and-dirty fix could be switching `&&` for `;` in order to ignore error 1 in the chain , but looking at the Dockerfile spec, I do believe it's better to avoid 3 commands in chain as an entrypoint.

Moreover, services aren't supposed to be up and running in the image / initial container state, and if they are enabled by default in /etc (I checked), in theory we don't need a restart, specially for cron, it's used by root already ?

What about MEMCACHED_ENABLE : it could / should control the state of service memcached, doesn't it ?

The strange thing is that I was able to run a docker geonode instance with success from the core repo 3.x. ...
So the explanation could lie somewhere in the Dockerfile(s) differences between repositories ?

**Comment by vijdz** [comment]
From another point of view, the cause of this error code could be that the built image is a frozen state, with a service up and running, so when docker is creating a container and sys / proc devices are mounted, somehow he sees a PID but it but can't be accessed via a socket outside of the main ENTRYPOINT process tree. There has to be something weird about the way docker is decomposing `&&` when the container is initiate.
Anyway, it may be some new version somewhere that is now returning an error code 1 on recent machines, where before it was just ignored.

**Comment by vijdz** [comment]
I was curious and tested it, and it did not work either.
But I think I found the problem. I was so confused by the service restart thing, and did not looked at my invoke.log, and it was stupid, sorry about that.

So I found this :
```python
GeoNode databases are up - executing command
**************************migrations*******************************
Traceback (most recent call last):
  File "manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 325, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/src/geonode/geonode/settings.py", line 44, in <module>
    if not SITEURL.endswith('/'):
NameError: name 'SITEURL' is not defined
```
Well I guess it was a REAL BAD idea to name my project geonode, since it's a mess for python imports ! I swear, I just wanted short container names and a cool url for my git repo "$group/geonode" ...

**Comment by t-book** [comment]
Ah yes! I ran in this some years before! We should prevent it!

**Comment by vijdz** [comment]
So do I leave this open ?
For the record, I changed everything except compose project name and it is running smoothly.
Also for the record, I was able to compose with specification v3.7 without issues.

About Docker version(s), do we still need to force API 1.24 ?
I saw it was first issued in 2018

**Comment by massoudhamad** [comment]
I am still getting this error in Ubuntu 20.04 geonode 3.2.x , any help will be appreciated @afabiani @ricardogsilva @t-book

**Comment by afabiani** [comment]
@massoudhamad you **should not** call a geonode-project instance geonode. Please, rename it to something else.

**Comment by espinafre** [comment]
I've just been bitten by this. A warning on the install documentation would help a lot!

**Comment by vijdz** [comment]
From the [README.md](https://github.com/GeoNode/geonode-project#create-a-custom-project):  
>NOTE: You can call your geonode project whatever you like except 'geonode'. Follow the naming conventions for python packages (generally lower case with underscores (_). In the examples below, replace {{ project_name }} with whatever you would like to name your project.
