### ISSUE TITLE
Change of database passwords not working

### ISSUE THREAD

**Issue by t-book** [GeoNode/geonode-project#173]
## Test 1: Change postgis passwords in running stack

With branch 3.2.x and docker try the following:

- fresh instance
- `docker-compose up -d --build`
- Instance is running

Change database passwords:

```
ALTER USER my_geonode_data WITH PASSWORD 'newpassword';
ALTER USER my_geonode WITH PASSWORD 'newpassword';

# test passwords (works)
psql -h localhost -p 5432 -U my_geonode_data -d my_geonode_data 
```

 Change Passwords in.env

```
"GEONODE_DATABASE=my_geonode",
"GEONODE_DATABASE_PASSWORD=newpassword",
"GEONODE_GEODATABASE=my_geonode_data",
"GEONODE_GEODATABASE_PASSWORD=newpassword",
```
Rebuild Django and celery.
```
`docker-compose up -d --build django celery`
```
Ends in error (invoke.log)

```
Traceback (most recent call last):
... ine 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: FATAL:  password authentication failed for user "my_geonode"
```

## Test 2: Set passwords on fresh start

Now even more strange:
```
# set passwords as shown above in .env (newpassword)
# prune the system (including volumes)
./docker-purge
docker-compose up -d --build --no-cache
```

The same error it looks like somehow only passwords `geonode` are working. 

> **Note this is also happening before this merge https://github.com/GeoNode/postgis-docker/pull/7!** Further, I can confirm that the new .env passwords are populated to the postgis container and hence should be read when initially creating the databases

---

@afabiani 
@gannebamm 

Am I doing something wrong or is it a regression?

**Comment by afabiani** [comment]
I guess you need to updated `DATABASE_URL` and `GEODATABASE_URL` accordingly too.

**Comment by t-book** [comment]
Oh, I see @afabiani 

the syntax:
```
{{project_name}}:geonode@db:5432
```
are username and password. Let me just try it. (A bit misleading in combination with the vars above if it's working I maybe I would add a short comment or update docs)

**Comment by gannebamm** [comment]
Yes, the `DATABASE_URL` vars are needed, too. And If you use the project based GeoServer Image, which does use postgres as geofence store, you shall see how that one get´s updated, too.
see: https://github.com/GeoNode/geonode-project/blob/master/docker/geoserver/templates/geofence/geofence-datasource-ovr.properties.j2

**Comment by t-book** [comment]
> There is no glory in practice but without practice, there is no glory!

Thanks to both of you! – I will leave a note in docs.
