### ISSUE TITLE
set postgis:13 tag for 3.2.x and 3.1.x

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode-project#175]
3.2.x [https://github.com/GeoNode/geonode-project/blob/3.2.x/docker-compose.yml#L5](https://github.com/GeoNode/geonode-project/blob/3.2.x/docker-compose.yml#L5)
3.1.x [https://github.com/GeoNode/geonode-project/blob/3.1.x/docker-compose.yml#L5](https://github.com/GeoNode/geonode-project/blob/3.1.x/docker-compose.yml#L5)

**Comment by afabiani** [comment]
Done through:

https://github.com/GeoNode/geonode-project/commit/4565f3ac680f5477e71143115f8d1bd6cbd42cb9

https://github.com/GeoNode/geonode-project/commit/749efbe6f2d079e8ca495228acb18e514470852d

https://github.com/GeoNode/geonode-project/commit/bf503642dbc303594bb2a977df3614bba8ca0622
