### ISSUE TITLE
django and celery services fail silently at running migrations

### ISSUE THREAD

**Issue by WernerRaath** [GeoNode/geonode-project#178]
I just ran a `docker-compose stop && docker-compose build && docker-compose up -d` after editing something in the `settings.py` file.

In this case my project name is `my_geonode`

Upon startup, my `celery` and `django` services both die when it says `running migrations`

```
django4my_geonode | -----------------------------------------------------
django4my_geonode | STARTING DJANGO ENTRYPOINT Wed May  5 09:37:47 UTC 2021
django4my_geonode | -----------------------------------------------------
django4my_geonode | DOCKER_API_VERSION=1.24
django4my_geonode | POSTGRES_USER=postgres
django4my_geonode | POSTGRES_PASSWORD=postgres
django4my_geonode | DATABASE_URL=postgis://my_geonode:geonode@db:5432/my_geonode
django4my_geonode | GEODATABASE_URL=postgis://my_geonode_data:geonode@db:5432/my_geonode_data
django4my_geonode | SITEURL=http://localhost/
django4my_geonode | ALLOWED_HOSTS=['django', 'localhost', 'localhost:None', 'geonode', 'django']
django4my_geonode | GEOSERVER_PUBLIC_LOCATION=http://localhost/geoserver/
django4my_geonode | MONITORING_ENABLED=True
django4my_geonode | MONITORING_HOST_NAME=geonode
django4my_geonode | MONITORING_SERVICE_NAME=local-geonode
django4my_geonode | MONITORING_DATA_TTL=365
django4my_geonode | waitfordbs task done
django4my_geonode | running migrations
django4my_geonode exited with code 1
```

How can I see what is causing this failure. Have tested DB connection params, so it's not that.

**Comment by JeffreyVRiemsdijk** [comment]
my celery instance is also stopping at running migrations. trying to find a solution as well to figure out what is happening.

**Comment by afabiani** [comment]
The file `invoke.log` should contain the full stacktrace

**Comment by WernerRaath** [comment]
@afabiani, thanks you legend! Is there a way to let logs be sent to **stdout** instead of the file?

**Comment by afabiani** [comment]
I guess it could be possible by removing **all** those redirects from the `entrypoint.sh` file

https://github.com/GeoNode/geonode-project/blob/master/entrypoint.sh#L15 and the others below...

**Comment by WernerRaath** [comment]
I think I'll make a pull request that accepts a new environment variable which will dictate logs to go either to a file or to stdout.

The reason for stdout being preferred is since it aligns with micro-service best practices to not send logs to files, but rather to `stdout` to be sent to some other logging service.

**Comment by afabiani** [comment]
sure, PRs are very welcome

**Comment by WernerRaath** [comment]
Submitted! https://github.com/GeoNode/geonode-project/pull/179

**Comment by afabiani** [comment]
Merged, thanks.
