### ISSUE TITLE
docker-entrypoint.sh overwrtites external ssl certificates

### ISSUE THREAD

**Issue by lpasquali** [GeoNode/geonode-project#201]
These lines in the docker-entrypoint.sh of nginx https://github.com/GeoNode/geonode-project/blob/e21cc1b398fe1b46042c766bfc276b798f11d4de/docker/nginx/docker-entrypoint.sh#L14-L21
 no matter the real expiration date (which should be checked with openssl), if the "file" for full certificates chain and private key are more than 365 days old they get overwritten no matter of the .env decision about how to handle certificates for a peculiar instance, it is like a "timebomb" ready to overwrite ssl certs where nginx  will be restarted after one year is passed respect the certs and private keys files timestamps

**Comment by giohappy** [comment]
@lpasquali what about this? Are you going to send a PR or is it already fixed?

**Comment by lpasquali** [comment]
> @lpasquali what about this? Are you going to send a PR or is it already fixed?
@giohappy 
this not has to be fixed in my opinion, the correct approach as documented is to make /geonode-certificates/foobar/ thus everything under `/geonode-certificates/autoissued/` is sane to be wiped out once a year @giohappy on mapstand I created  `/geonode-certificates/mapstand` for this purpose and it never gets overwritten.

**Comment by giohappy** [comment]
so should we close this issue?

**Comment by lpasquali** [comment]
@giohappy for me yes
