### ISSUE TITLE
certbot fails when using LETSENCRYPT_MODE=staging 

### ISSUE THREAD

**Issue by frafra** [GeoNode/geonode-project#203]
```
Trying to get STAGING certificate
--server value conflicts with --staging
 
Failed to get the certificates !
```

https://github.com/GeoNode/geonode-project/blob/e21cc1b398fe1b46042c766bfc276b798f11d4de/docker/letsencrypt/docker-entrypoint.sh#L20

https://acme-staging-v02.api.letsencrypt.org/directory should be used instead, according to https://letsencrypt.org/docs/staging-environment/.

**Comment by msalmanfarisi** [comment]
i have also been facing the same problem. any solutions ?

**Comment by frafra** [comment]
@msalmanfarisi I just proposed a PR. Could you please test it? You should apply the change and rebuild the images.
