### ISSUE TITLE
[DOCKER] GeoNode admin password is not persisted between containers re-creation or restarts

### ISSUE THREAD

**Issue by drumbsd** [GeoNode/geonode-project#211]
Problem:

GeoNode admin password seems to be reset upon container restart.

Steps to reproduce:

* Run the enviroment using docker-compose as written in documentation (branch 3.3.x)
* Login on geonode with admin/admin
* Change admin password
* Restart containers with "docker-compose restart"
* You see that admin password is revert to default "admin"

Branch 3.3.x

**Comment by etj** [comment]
"It's a feature, not a bug!"

You have to set the new password in the .env file as `GEOSERVER_ADMIN_PASSWORD` env var.
Each time geonode is restarted, the geoserver pw will be set to that pw:

https://github.com/GeoNode/geonode-project/blob/3.3.x/entrypoint.sh#L73 :
```bash
        /usr/local/bin/invoke geoserverfixture > /usr/src/{{project_name}}/invoke.log 2>&1
```

https://github.com/GeoNode/geonode-project/blob/3.3.x/tasks.py#L256-L259
```python
@task
def geoserverfixture(ctx):
    print("********************geoserver fixture********************************")
    _geoserver_info_provision(f"{os.environ['GEOSERVER_LOCATION']}rest/")
```

https://github.com/GeoNode/geonode-project/blob/01bf864445486d2f6ab8350c6ddc2dd359561bc3/tasks.py#L405-L428
```python
def _geoserver_info_provision(url):
    from django.conf import settings
    from geoserver.catalog import Catalog
    print("Setting GeoServer Admin Password...")
    cat = Catalog(
        url,
        username=settings.OGC_SERVER_DEFAULT_USER,
        password=settings.OGC_SERVER_DEFAULT_PASSWORD
    )
    headers = {
        "Content-type": "application/xml",
        "Accept": "application/xml"
    }
    data = f"""<?xml version="1.0" encoding="UTF-8"?>
<userPassword>
    <newPassword>{(os.getenv('GEOSERVER_ADMIN_PASSWORD', 'geoserver'))}</newPassword>
</userPassword>"""

    response = cat.http_request(f"{cat.service_url}/security/self/password", method="PUT", data=data, headers=headers)
    print(f"Response Code: {response.status_code}")
    if response.status_code == 200:
        print("GeoServer admin password updated SUCCESSFULLY!")
    else:
        logger.warning(f"WARNING: GeoServer admin password *NOT* updated: code [{response.status_code}]")
```

**Comment by randomorder** [comment]
the issue is about GeoNode passwd not GeoServer's but this answer applies to https://github.com/GeoNode/geonode-project/issues/209

**Comment by giohappy** [comment]
@etj regarding `GEOSERVER_ADMIN_PASSWORD` see my comment https://github.com/GeoNode/geonode-project/issues/209#issuecomment-905351269

**Comment by giohappy** [comment]
Apparently a mechanism to the one used for `GEOSERVER_ADMIN_PASSWORD` should prepare the fixture with the password from the `ADMIN_PASSWORD`


https://github.com/GeoNode/geonode-project/blob/3.3.x/tasks.py#L282-L289
```python
@task
def updateadmin(ctx):
    print("***********************update admin details**************************")
    ctx.run("rm -rf /tmp/django_admin_docker.json", pty=True)
    _prepare_admin_fixture(
        os.environ.get('ADMIN_PASSWORD', 'admin'),
        os.environ.get('ADMIN_EMAIL', 'admin@example.org'))
    ctx.run(f"django-admin.py loaddata /tmp/django_admin_docker.json \
--settings={_localsettings()}", pty=True)
```

@drumbsd we will need to print some logs to see if the fixture is correctly created.

**Comment by giohappy** [comment]
@drumbsd for ADMIN_PASSWORD please check if `/tmp/django_admin_docker.json` exists and how it's populated. I can see it inside the django container of stable demo.

**Comment by drumbsd** [comment]
It's present inside django container. Is this ( I removed sha password)

```
[
  {
    "fields": {
      "date_joined": "2021-08-30T11:44:08.191Z",
      "email": "admin@development.demo.geonode.org",
      "first_name": "",
      "groups": [],
      "is_active": true,
      "is_staff": true,
      "is_superuser": true,
      "last_login": "2021-08-30T11:44:08.191Z",
      "last_name": "",
      "password": "xxxxxxxxxxxxxxxxxxxxxxxxxx",
      "user_permissions": [],
      "username": "admin"
    },
    "model": "people.Profile",
    "pk": 1000
  }
]
```

@giohappy

**Comment by drumbsd** [comment]
@giohappy  The question is:

* Where the new admin password is stored once is changed? DB? Some local file?
* Why, when I restart django container, the password is reset to the original "admin" 

Moreover, this command:

```
django-admin.py loaddata /tmp/django_admin_docker.json
```

contained inside the task **updateadmin** is executed on every start? Because, if it's the case, is clear for me why the password is not persistent.

**Comment by giohappy** [comment]
>Where the new admin password is stored once is changed? DB? Some local file?

DB. `django-admin.py loaddata` is a command that loads a JSON into the DB.

>Why, when I restart django container, the password is reset to the original "admin"

This is what we need to investigate @drumbsd. In theory the `django-admin.py loaddata /tmp/django_admin_docker.json` [is executed on every restart](https://github.com/GeoNode/geonode-project/blob/3.3.x/entrypoint.sh#L76), and it should persist the `ADMIN_PASSWORD` value to the DB. Apparently it doesn't happen and we should check if the command executes and with which env vars. I would start by putting some logs before the task is executed inside the `entrypoint.sh`

**Comment by giohappy** [comment]
There was a misunderstanding. The issue is that the password set through the django admin is not retained between restarts. This is the expected behaviour (although maybe not the desired one), since the `updateadmin` task is executed on each restart. It's not a one-off execution, as it happens for [this block of tasks](https://github.com/GeoNode/geonode-project/blob/3.3.x/entrypoint.sh#L57-L66).

@afabiani I don't remember when and why this task was moved outside of init lock, but in my opinion it should be executed only once (unless `FORCE_REINIT` is set). The password set with django admin should be honored.

**Comment by giohappy** [comment]
I suggest to move the task invocation inside the initialization block. It's the most safe and conservative approach. In case we can add a print statement inside the invoke logs which reminds that the GeoNode password hasn't been updated. 

In case we need to update it from the env the `FORCE_REINIT` env var must be used.

**Comment by simboss** [comment]
@giohappy you are suggesting to whom? @drumbsd ?

**Comment by giohappy** [comment]
I was giving a hint to the DevOps team and any other GeoNode dev to consider the option proposed in my previous comments, which I already presented to @drumbsd.

The option is to move the `updateadmin` task inside [this block](https://github.com/GeoNode/geonode-project/blob/3.3.x/entrypoint.sh#L57-L66). This way the task will only run the first time or in case the `FORCE_REINIT` env var is set. 
The final effect is that the GeoNode admin password will be overwritten by `ADMIN_PASSWORD` only in these two cases, otherwise the password set in the DB is maintained.

I wanted the opinion from the DevOps on this. If we all agree we can do it and update the documentation.

**Comment by drumbsd** [comment]
For me it makes sense. I'll do it.
