### ISSUE TITLE
GeoServer docker build failing.

### ISSUE THREAD

**Issue by drumbsd** [GeoNode/geonode-project#226]
For some strange reason, the GeoServer Dockerfile , even if uses tomcat9-jre8 , tries to install openjdk-8-jdk

```
RUN apt-get update \
    && apt-get install -y procps less \
    && apt-get install -y openjdk-8-jdk python3 python3-pip python3-dev \
    && chmod +x /usr/local/tomcat/tmp/set_geoserver_auth.sh \
```

From this morning seems that openjdk-8-jdk is no longer available for distribution on which the docker image was created, generating the error:

**E: Unable to locate package openjdk-8-jdk**

I tried to remove it and rebuild the GeoServer and all works fine. I think we can remove it since jre8 is already installed on the tomcat9-jre8 image. If it is ok for you @afabiani , I can do a PR for master and for 3.2.x and 3.3.x

**Comment by afabiani** [comment]
@drumbsd sure go ahead thanks.

Can you also make a PR an geonode core docker file?

**Comment by drumbsd** [comment]
@afabiani Nothing related to openjdk-8-jdk on GeoNode Dockerfile. I think it is a specific GeoServer Dockerfile problem.
