### ISSUE TITLE
Wrong URL inside Admin profile -> GeoServer Tab.

### ISSUE THREAD

**Issue by drumbsd** [GeoNode/geonode-project#230]
Hello, I'm using 3.3.x. If you login as admin inside geonode, goes on profile page, then click on GeoServer link you see that the code seems to use the **GEOSERVER_LOCATION** value instead of use **GEOSERVER_PUBLIC_LOCATION**

So the link is not working.

![image](https://user-images.githubusercontent.com/6428880/132230455-736f9370-25cd-47d1-b58f-34abdeae86a7.png)

![image](https://user-images.githubusercontent.com/6428880/132230356-faacd8b3-b921-48e8-b570-0d26fa935035.png)

**Comment by giohappy** [comment]
Issue moved to [GeoNode/geonode #8051](https://github.com/GeoNode/geonode/issues/8051) via [**ZenHub**](https://www.zenhub.com/)
