### ISSUE TITLE
Error installation

### ISSUE THREAD

**Issue by guisz1** [GeoNode/geonode-project#232]
error starting geonode build and always returns this failure
![Captura de tela de 2021-09-09 10-59-19](https://user-images.githubusercontent.com/16584514/132700168-d94668d2-c260-496c-aed7-eb897a649bb4.png)
ERROR: pull access denied for my_geonode_django, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
WARNING! This will remove:
  - all stopped containers
  - all networks not used by at least one container
  - all images without at least one container associated to them
  - all build cache

**Comment by guisz1** [comment]
![image](https://user-images.githubusercontent.com/16584514/132892206-dd7f0662-9bf3-498d-8964-94b3d3f4b942.png)

**Comment by afabiani** [comment]
@guisz1 please update your requirements.txt file accordingly to https://github.com/GeoNode/geonode-project/commit/078ef5ebff3af2fea60d9c178f33e479ba3d6838

**Comment by guisz1** [comment]
thank you thats work
