### ISSUE TITLE
docker-build.sh commands.

### ISSUE THREAD

**Issue by drumbsd** [GeoNode/geonode-project#239]
Hello, currently the docker-build.sh file is this:

```
docker-compose build --no-cache; docker-compose stop; docker-compose up -d; docker system prune -a
```

Is there a specific reason why && is not used? Since these commands needs to be executed in series, and only if the previous command had a positive result, why not change it in this way?

```
docker-compose build --no-cache && docker-compose stop && docker-compose up -d && docker system prune -a
```

If, for example, the docker-compose build --no-cache fails, as happened to me today, there's no reasons to stop docker-compose, run docker-compose up again and do a system prune. I think they should be executed in a real AND chain.

**Comment by giohappy** [comment]
Please @drumbsd send a PR.
To be honest I'm not sure if it's safe to have the `docker system prune -a` at the end.
