### ISSUE TITLE
Rename .env file

### ISSUE THREAD

**Issue by etj** [GeoNode/geonode-project#241]
Users will probably customize vars in `.env`, so we don't want such a file to be stored in git repos.
If private info are hidden in the stored version, we'll get conflict at every git pull.
Furthermore, if the vanilla .env changes (vars added, etc), it will be difficult to perform a diff to find out what's changed.

- [ ] move `.env` to `.env_sample`
- [ ] update doc

**Comment by frafra** [comment]
May I suggest avoiding the `.env` file entirely and just have variables shared between containers in `docker-compose.yml`? It is much simpler to figure out which container relies on what, avoiding exposing variables to containers that do not need them (which improves security), without having to care about hidden files that could affect how `docker-compose` behaves. There are YAML anchors nowadays.

**Comment by giohappy** [comment]
@frafra I see your point. Currently the `.env` file is passed to `django`, `celery`, `geoserver` and `db` services. Breaking the .env file apart and putting any shared env var inside YAML anchors might be nice, but it must done carefully to be sure that we're not losing any env along the way.

For the moment I'd do the small improvement proposed by @etj, then feel free to submit a PR for your proposa.
