### ISSUE TITLE
Collect info into invoke.log file

### ISSUE THREAD

**Issue by etj** [GeoNode/geonode-project#242]
Using the `>` redirection, the file will be recreated each time `invoke` is called
https://github.com/GeoNode/geonode-project/blob/b6a423ba476c12a046463ab9060a11fe09e2a0b9/src/entrypoint.sh#L12

Pls use `>>` in order to append info in the same file.

We may want to recreate the file when the FORCE_REINIT is provided.

**Comment by frafra** [comment]
Could we please avoid using such redirects to files at all? Loggers output should be stdout/stderr when using containers, not files usually.

**Comment by afabiani** [comment]
In the most recent configurations a variable drive the way how you want the logs outputted. The default is `stdout`

**Comment by etj** [comment]
@afabiani The problem is exactly there:
https://github.com/GeoNode/geonode-project/blob/b6a423ba476c12a046463ab9060a11fe09e2a0b9/src/entrypoint.sh#L6-L15

When the output is not stdout but a file, the file is recreated over and over (see the single `>` in line 12).

**Comment by giohappy** [comment]
I agree with @etj about the append redirection. BTW we sould take care to rotate it, although invoke logs shouldn't grow much in time.
