### ISSUE TITLE
Check tests on MONITORING_ENABLED env var

### ISSUE THREAD

**Issue by etj** [GeoNode/geonode-project#255]
Some code is performing checks like this:
```python
    if os.environ.get('MONITORING_ENABLED', False):
```

When the given env var is defined, even if its string value is "False", it will be evaluated as `True`.

e.g.: this commit:

https://github.com/GeoNode/geonode-project/commit/131910ff67ac2ee7a018ece6b6ca855bd6f8559c#diff-2e746c9eacad6e2c2fdefdc6a665b5ce4607ea384ebf97a729044b79acc778d6R278

Please note that since the `MONITORING_ENABLED` env var is properly parsed elsewhere, this misalignment may cause errors; for instance in the entrypoint you would get errors like this:
```
**************************update geoip*******************************
Unknown command: 'updategeoip'. Did you mean updatemaplayerip?
Type 'django-admin.py help' for usage.
```

**Comment by giohappy** [comment]
`ast.literal_eval(os.environ.get('MONITORING_ENABLED', False))` is probably best for this.
