### ISSUE TITLE
nginx *.envsubst cannot be found

### ISSUE THREAD

**Issue by frafra** [GeoNode/geonode-project#265]
https://github.com/GeoNode/geonode-project/blob/7393bb71b14691d4ce135d84fd3c1b1b0c9c2eb5/docker/nginx/Dockerfile#L5-L7

These files are not found as a volume is mounted over the folder where they are stored:

https://github.com/GeoNode/geonode-project/blob/7393bb71b14691d4ce135d84fd3c1b1b0c9c2eb5/docker-compose.yml#L67

Wouldn't be better to comment that line and/or move the templates elsewhere?

**Comment by giohappy** [comment]
@frafra what do you mean? The WORKDIR sets the directory where the ADD command will copy the files, and that folder is the one mounted as a volume. What's wrong here?

**Comment by frafra** [comment]
Docker behaves differently if a named volume is used or if a directory is used (which is a terrible design choice in my opinion, probably related with how folders are overlayed).

When you run nginx using volumes, there is no problem.
If you use folders instead, the mounted directory is mounted "on top" of the container, so `/etc/nginx` gets overwritten entirely, and these files are not accessible anymore.

I would suggest a solution which is not based on how volumes are currently working on Docker, and adopting something which can also work with directories and other mechanisms.

**Comment by giohappy** [comment]
@lpasquali can you please review these points from @frafra?

**Comment by lpasquali** [comment]
@giohappy I agree with @frafra envision, we should drop the habit of the nginx volume (main cause of several issues with nginx configuration persistence, ssl certificates removed or ulinked upon rebuilts and so on), as persistence of such data gives  more problems than benefits.
The "envsubst" process on how nginx gets configured upon rebuilds should be volatile and always created from scratch, handling the variety of cases for ssl encryption (letsencrypt or purchased certificates).
It might take some work to get rid of nginx-volume though and it would imply some amount of work for each upgrade to adapt old projects to it (where needed), but once done upgrades would be much more smoother and with less prerequisites to be taken into account.

**Comment by giohappy** [comment]
@frafra are you planning to submit a PR for that?

**Comment by frafra** [comment]
We can then drop the persistence of that folder entirely then.
@giohappy yes, that is trivial

**Comment by gannebamm** [comment]
> Docker behaves differently if a named volume is used or if a directory is used (which is a terrible design choice in my opinion, probably related with how folders are overlayed).
> 
> When you run nginx using volumes, there is no problem. If you use folders instead, the mounted directory is mounted "on top" of the container, so `/etc/nginx` gets overwritten entirely, and these files are not accessible anymore.
> 
> I would suggest a solution which is not based on how volumes are currently working on Docker, and adopting something which can also work with directories and other mechanisms.

I actually was puzzled why sometimes I get this kind of strange behaviour! Good catch @frafra
