### ISSUE TITLE
docker install 3.2.x - Unexpected error! - Unknwon Error Code uplading a layer

### ISSUE THREAD

**Issue by ferchimi** [GeoNode/geonode-project#278]
Hi there
I have a functioning geonode proyect running on geonode 3.2.x installed on docker-compose
When I try to upload a layer I have the following error message after the green bar completes
"Unexpected error! - Unknwon Error Code. Contact the system administrator for more information regarding this error message."
No logs are seen anywhere with docker-compose logs -f, so I just can't see where the problem is
Regards, Fernando

**Comment by frafra** [comment]
See #266. You would also need to mount `invoke.log` as file (this has been fixed in 3.3), after touching it. You can open the file within the container otherwise.

**Comment by ferchimi** [comment]
> See #266. You would also need to mount `invoke.log` as file (this has been fixed in 3.3), after touching it. You can open the file within the container otherwise.

Thanks for your reply
I'm pretty now to this debugging, so I dont understand/know what service would be this log for (geoserver, celery, etc) and where I can find this invoke.log inside the already running container 
Regards!

**Comment by frafra** [comment]
It is inside the geonode container:
https://github.com/GeoNode/geonode-project/blob/4993e318a495567351b367a93461c5dc5ec074af/entrypoint.sh#L15

geonode stores the logs when it starts. After that, logs are stored under `/var/log/geonode.log`.

**Comment by ferchimi** [comment]
This is the point where I get really confused with geonode in general, as it seems that some users have logs and features that some other users don't
/etc/nginx # find / -name \*.log
/var/log/nginx/access.log
/var/log/nginx/error.log


> It is inside the geonode container:
> 
> https://github.com/GeoNode/geonode-project/blob/4993e318a495567351b367a93461c5dc5ec074af/entrypoint.sh#L15
> 
> geonode stores the logs when it starts. After that, logs are stored under `/var/log/geonode.log`.

This is the point where I get really confused with geonode in general, as it seems that some users have logs and features that some other users just don't, I see other users having similar issues to mine, but no solutions, and my installation is as vanilla is it comes

This is the geonode container, no geonode.log, no invoke.log, nowhere

/etc/nginx # find / -name \*.log
/var/log/nginx/access.log
/var/log/nginx/error.log

I'm using 3.2 since 3.1 (which used to work fine for me) fails at docker-compose build since the geoserver.war file does not exist anymore in dropbox (where it tries to get it from) and no other war is useful, and 3.3 does not let me login geoserver in any way due to a "privacy issue" -> tried from localhost, local ip and public ip and public URL, standard install

**Comment by frafra** [comment]
You are looking in the nginx container. Look inside the django container, which contains the geonode code. The naming of the containers is confusing.

You should use the latest version, as it includes various bugfixes and improvements. If you have issues with 3.3, just open a new issue for that.

**Comment by ferchimi** [comment]
> You are looking in the nginx container. Look inside the django container, which contains the geonode code. The naming of the containers is confusing.
> 
> You should use the latest version, as it includes various bugfixes and improvements. If you have issues with 3.3, just open a new issue for that.

I found /geoserver_data/data/logs/geoserver.log in django container which has some logs from last night, but right now it doesnt generate any
2022-03-25 04:21:14,747 WARN [protocol.ResponseProcessCookies] - Invalid cookie header: "Set-Cookie: sessionid=5h5gjkjmxj0bsp74eqsv20il6v97sv7n; expires=Fri, 08 Apr 2022 04:21:14 GMT; HttpOnly; Max-Age=1209600; Path=/; SameSite=Lax". Invalid 'expires' attribute: Fri, 08 Apr 2022 04:21:14 GMT
2022-03-25 04:21:14,766 WARN [protocol.ResponseProcessCookies] - Invalid cookie header: "Set-Cookie: sessionid=b0ahc1b0m7tuz0kytjusii7jhuke5stq; expires=Fri, 08 Apr 2022 04:21:14 GMT; HttpOnly; Max-Age=1209600; Path=/; SameSite=Lax". Invalid 'expires' attribute: Fri, 08 Apr 2022 04:21:14 GMT
2022-03-25 04:22:45,246 WARN [protocol.ResponseProcessCookies] - Invalid cookie header: "Set-Cookie: sessionid=0fgdvljb1sffr9f7va2zz74twzha88t6; expires=Fri, 08 Apr 2022 04:22:45 GMT; HttpOnly; Max-Age=1209600; Path=/; SameSite=Lax". Invalid 'expires' attribute: Fri, 08 Apr 2022 04:22:45 GMT
2022-03-25 04:22:45,273 WARN [protocol.ResponseProcessCookies] - Invalid cookie header: "Set-Cookie: sessionid=wf8cob8ci0tmn9b0d4hsscdhhfh4xjia; expires=Fri, 08 Apr 2022 04:22:45 GMT; HttpOnly; Max-Age=1209600; Path=/; SameSite=Lax". Invalid 'expires' attribute: Fri, 08 Apr 2022 04:22:45 GMT
2022-03-25 04:26:17,956 WARN [geofence.cache] - org.geoserver.geofence.cache.CachedRuleReader$NoAuthException: Can't auth user [admin]
2022-03-25 04:26:17,956 WARN [geoserver.security] - Failed login, user admin from 192.168.16.4, forwarded for 190.55.195.170, 10.10.50.11

that's it

The uploading error still persist and a tail -f of this particular log didn't catch anything
Thnaks
PS: I have to go production with something that moderately works for now, and 3.2 is the closest I can get right now

**Comment by frafra** [comment]
I guess that both 3.2 and 3.3 have been misconfigured, but it would be nice to get more logs, from the web browser network tab for the failed request, see what the server replied to which request and such.
I would suggest double-checking your .env file. You could also need to re-init geonode. As you do not have any data stored, you can just remove the volumes.

**Comment by ferchimi** [comment]
> I guess that both 3.2 and 3.3 have been misconfigured, but it would be nice to get more logs, from the web browser network tab for the failed request, see what the server replied to which request and such. I would suggest double-checking your .env file. You could also need to re-init geonode. As you do not have any data stored, you can just remove the volumes.

I have no problem with starting over, but I sincerely don't know what to look for in the .env file
as i see, the key points are:
SITEURL=http://geonode.sisa.msal.gov.ar/

GEOSERVER_WEB_UI_LOCATION=http://geonode.sisa.msal.gov.ar/geoserver/
GEOSERVER_PUBLIC_LOCATION=http://geonode.sisa.msal.gov.ar/geoserver/
GEOSERVER_LOCATION=http://geoserver:8080/geoserver/

GEONODE_LB_HOST_IP=geonode.sisa.msal.gov.ar
HTTP_HOST=geonode.sisa.msal.gov.ar
HTTPS_HOST=

HTTP_PORT=80
HTTPS_PORT=443

The DB configuration works just fine, by now I'm using the default docker postgres with no changes
I also have doubts about how the changes are applied, for instance, i dont know if i modify the .env file changing the hosts/ports and/or URLs it takes effect executing docker-compose down / docker-compose up, or if I have to start over
I've seen "the env var FORCE_REINIT" but I don't know where to set it (is it in the .env file, or set FORCE_REINIT=1 or so in bash before docker-compose up -d?)

knowing this stuff would be of great help
thank you very much

**Comment by frafra** [comment]
I get a 5xx HTTP error at the moment.
The snippet you posted seems correct.
You should enable debug mode, using `DEBUG=True` first.
Setting `ASYNC_SIGNALS=False` could help in some cases.

**Comment by ferchimi** [comment]
> I get a 5xx HTTP error at the moment. The snippet you posted seems correct. You should enable debug mode, using `DEBUG=True` first. Setting `ASYNC_SIGNALS=False` could help in some cases.

I was restarting it, now it's down, I'll try some things and be back

**Comment by ferchimi** [comment]
I fixed a hostname that was wrong, I made FORCE_REINIT=true, now the error turned to
Unexpected error! - Unknwon Error Code. Contact the system administrator for more information regarding this error message. Additional info: [Client Error: Bad Request
Unexpected exception [Errno 2] No such file or directory: '/mnt/volumes/statics/static/tmptxusoauh']

at least is something

**Comment by ferchimi** [comment]
I started over and changed all http to the site to https, now it works like a charm, in fact as never before
Thank you for all the assistance
I'm closing the issue
