### ISSUE TITLE
Adapt for production using Docker

### ISSUE THREAD

**Issue by olivierdalang** [GeoNode/geonode-project#30]
Hi !

I've been trying out this project using Docker. I'm currently have some problems running it with Docker (probably linked to https://github.com/GeoNode/geonode-project/issues/5 ), but will probably have that sorted out at some point.

I think it's very promising, as it makes it very easy to develop a custom Geonode project without all the hassle of configuring all required services.

However, going from there to production is still very involved.

Here are a few problems I noticed :

- Images have no tags, which mean `docker-compose up` can pull a different image at anytime (whenever a new postgres image is released for example)
- Some services Dockerfiles are stored in other repo. Since they are (I think) specific to geonode-project, it would make more sense to keep them in the same repo (e.g. terranodo/nginx:geoserver and waybarrios/geoserver). This would make it much easier to adapt the setup if needed.
- Some critical actions are not enforced (set the public URL, change geoserver default admin login, ...)
- `settings.py` looks overwhelming, especially since it is supposed to inherit from default geonode settings
- Django runs in debug mode and serves static/media files, which could be done by nginx
- Django runs using dev server, instead of uwsgi or other more robust python server
- Nothing about https encryption
- Nothing about data backup
- Some of the docker images are quite heavy to pull (they could probably be optimized, which can be a big deal in some places of the world).

Do you think providing a production-ready, easy-to-customize and almost-one-line-deployable setup through Docker is a realistic goal ? Is it in the scope of geonode-project ?

I'm currently working on exactly this (I started from scratch, also I'm relatively new to Geonode and Docker) and am willing to contribute to that goal.

Kind regards,

Olivier

**Comment by francbartoli** [comment]
@olivierdalang thanks for your feedbacks and good if you have patches/PRs to improve the docker stuff here. However the goal of this project is to start the customization of a GeoNode instance regardless about Docker.
I'd suggest before digging into this to take more confidence with GeoNode dockerization and the images it is using from [dockerhub](https://hub.docker.com/r/geonode/).
Several issues that you reported can be assigned to the GitHub repos of previous images. I'm going to report them myself.
Others are still work in progress, maybe you can start following this [PR](https://github.com/GeoNode/geonode/pull/3538).
If you want to contribute I'd suggest to join the devel [list](mailto:geonode-devel@lists.osgeo.org) and start there discussions about features
