### ISSUE TITLE
pygdal minimum version requirements

### ISSUE THREAD

**Issue by Roburetto** [GeoNode/geonode-project#31]
Requirements for 2.8.0 include:  pygdal==2.1.3.3
[Debian Stretch version is 2.1.2.3](https://packages.debian.org/stretch/gdal-bin)
Can geonode be properly run with gdal 2.12 instead of 2.1.3?

**Comment by francbartoli** [comment]
Closed by https://github.com/GeoNode/geonode-project/commit/26236acbd6af4f487a714e4a96e0016c5b652d3e
