### ISSUE TITLE
Application labels aren't unique, duplicates: ows_api

### ISSUE THREAD

**Issue by Roburetto** [GeoNode/geonode-project#32]
While trying to install 2.8.0, paver setup fails with:
django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: ows_api

Full details:
(geonode) geo@debian:/home/geonode/my_geonode$ DJANGO_SETTINGS_MODULE=my_geonode                                         .settings paver setup
---> pavement.setup
---> pavement.setup_geoserver
rmtree path('geoserver/data')
---> pavement.setup_qgis_server
---> pavement.updategeoip
 python manage.py updategeoip -o
Traceback (most recent call last):
  File "manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/home/geo/Envs/geonode/local/lib/python2.7/site-packages/django/core/man                                         agement/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/geo/Envs/geonode/local/lib/python2.7/site-packages/django/core/man                                         agement/__init__.py", line 328, in execute
    django.setup()
  File "/home/geo/Envs/geonode/local/lib/python2.7/site-packages/django/__init__                                         .py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/geo/Envs/geonode/local/lib/python2.7/site-packages/django/apps/reg                                         istry.py", line 89, in populate
    "duplicates: %s" % app_config.label)
django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, d                                         uplicates: ows_api

Captured Task Output:
---> pavement.setup
---> pavement.setup_geoserver
rmtree path('geoserver/data')
---> pavement.setup_qgis_server
---> pavement.updategeoip
 python manage.py updategeoip -o

Build failed running pavement.setup: Subprocess return code: 1

**Comment by Roburetto** [comment]
Hum. If I comment out Line 348 of settings.py it seems to work:
#INSTALLED_APPS += ('geonode.contrib.ows_api',)
Does this mean a personalized ows_api must be set somewhere? Pardon my ignorance, but I find no reference in the documentation...

**Comment by Roburetto** [comment]
Nevermind. 
It seems I did not follow instructions to the letter. Namely [the portion](http://docs.geonode.org/en/master/tutorials/install_and_admin/geonode_install/create_geonode_db.html): "Revert to default site settings. You need to revert some customizations of the my_geonode local_settings"

**Comment by davekennewell** [comment]
I have this issue when installing geonode 2.8.0 followed by creating a geonode-project from the template.

Commenting out Line 348 of settings.py fixes it, as Roburetto suggests. 

I'm not sure what the ows_api contrib app actually does, but generally we shouldn't have contrib apps turned on by default? Maybe someone who knows what it does can tell us if we should have it on or off in this repo?

Thanks!
