### ISSUE TITLE
Configure UTF-8 encoding for shapefiles in Geoserver by default?

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode-project#395]
Geoserver encods shapefiles as ASCII by default. Setting `-DGS-SHAPEFILE-CHARSET=UTF-8` is required to enable UTF-8 encoding.
What about setting this by default [here](https://github.com/GeoNode/geonode-project/blob/master/docker/geoserver/Dockerfile#L111)?

**Comment by t-book** [comment]
+1

**Comment by afabiani** [comment]
@giohappy ok, even if that variable will be then overridden by this one [here](https://github.com/GeoNode/geonode-project/blob/master/.env.sample#L109)

**Comment by giohappy** [comment]
@afabiani right, so we should also set it inside `.env.sample `
