### ISSUE TITLE
Unable to Connect to MapServer Web Service

### ISSUE THREAD

**Issue by tiqvahub** [GeoNode/geonode-project#420]
Hi developers,

I've had very successful connection using the [URL](http://toposerver.topomen.com/toposerver?MAP=MS_TOPOMEN) in QGIS, but I can never get it through by using GeoNode Remote Services connections. It seems that there is an issue with GeoNode for reading MapServer WMS requests. Could anyone confirm any problem regarding MapServer web services based on the provided URL?

**Comment by giohappy** [comment]
@tiqvahub the problem with that service is that the reported OnlineResource inside the [GetCapabilities](http://toposerver.topomen.com/toposerver?MAP=MS_TOPOMEN&service=WMS&version=1.3.0&request=GetCapabilities&MAP=MS_TOPOMEN) response links to http://45.190.248.136/toposerver?MAP=MS_TOPOMEN&, which cannot be reached.

![image](https://user-images.githubusercontent.com/571129/228890079-a02fa93c-1b6a-498c-a519-d829f1ab9463.png)
