### ISSUE TITLE
Geonode 4.0 search/filtering removes date range option

### ISSUE THREAD

**Issue by gjsa73** [GeoNode/geonode-project#426]
Geonode 3.x provided the option to search using specific date ranges in dataset metadata:
https://docs.geonode.org/en/3.3.x/usage/data/finding_data.html

Geonode 4.0 no longer includes a date option for searching/filtering:
![image](https://user-images.githubusercontent.com/21994806/235046934-2ca51fb9-c1ed-412b-a266-3be828e9a43e.png)

**Comment by giohappy** [comment]
@gjsa73 there are plans to reintroduce the dates filter in version 4.2.0.
