### ISSUE TITLE
Docker CollectStatic

### ISSUE THREAD

**Issue by indeOWS** [GeoNode/geonode-project#43]
Hi All,

I am trying to run docker-compose exec django django-admin.py collectstatic --noinput on GeoNode_Project@2.10rc4 instance. The response is: 2 static files copied to '/mnt/volumes/statics/static', 1716 unmodified. But the subdirectories ./volumes/statics/static do not exist. The directory static_root was not created either. Any comment on that will be very appreciated it. 
Thank you very much for your time in advance

**Comment by indeOWS** [comment]
Docker World...

**Comment by d3netxer** [comment]
did you figure this out @juliermegeotube ?
