### ISSUE TITLE
404 on thumbnails & other element 

### ISSUE THREAD

**Issue by bangkoor** [GeoNode/geonode-project#44]
I have installed Geonode on Ubuntu in a client machine using VirtualBox. The network setting is NAT with port forwarding. So I can access the app from host machine using a port.

The problem is I got 404 on some elements such as thumbnails and image. It is because they are still on the original URL without port.

example:
http://**localhost**/uploaded/thumbs/layer-43ff4bd2-b699-11e8-87ab-0800272d59b9-thumb.png
This is the url as set in client machine. But in host machine, it still the same, without port. It should be:
http://**localhost:82**/uploaded/thumbs/layer-43ff4bd2-b699-11e8-87ab-0800272d59b9-thumb.png

So how to fix this? Is it possible?

**Comment by simod** [comment]
hi you can use "geonode updateip -p localhost:82" to fix it.

ps please use the mailing list to ask for support
