### ISSUE TITLE
paver sync default_oauth_apps.json on 2.8 branch from master

### ISSUE THREAD

**Issue by t-book** [GeoNode/geonode-project#47]
Hi,

paver sync is failing in 2.8 branch because of:
- created
- algorithm
- updated 
https://github.com/GeoNode/geonode-project/blob/2.8/fixtures/default_oauth_apps.json

Is it possible that this has been accidentally pulled from master?

**Comment by afabiani** [comment]
@t-book yes, must be reverted. Thanks for reporting

**Comment by t-book** [comment]
+1

**Comment by afabiani** [comment]
@t-book should be ok now

**Comment by t-book** [comment]
@afabiani Grazie Alessio. Yes it works now. Thanks!
