### ISSUE TITLE
 __version__() in 2.8 branch

### ISSUE THREAD

**Issue by t-book** [GeoNode/geonode-project#48]
@afabiani shouldn´t __init__.py in 2.8 branch say 2.8.1 or 2.8.x?

`__version__ = (2, 7, 7, 'unstable', 0)`
https://github.com/GeoNode/geonode-project/blob/2.8/project_name/__init__.py

**Comment by afabiani** [comment]
@t-book +1

will change accordingly. Thanks for looking.
