### ISSUE TITLE
It doesn't work to organize resources by most recent, most popular or alphabetical order

### ISSUE THREAD

**Issue by gisdata-es** [GeoNode/geonode-project#485]
In version 4.1.2.dev0 it does not work to organize the list of resources by alphabetical criteria, most popular or most recent.
![image](https://github.com/GeoNode/geonode-project/assets/112013006/2e0babd3-9df4-465b-aa4a-24a702540180)

I have done tests at: https://stable.demo.geonode.org/catalogue/#/?sort=-date

**Comment by etj** [comment]
Dup of https://github.com/GeoNode/geonode/issues/11424

**Comment by giohappy** [comment]
I'm closing this since we have reopened https://github.com/GeoNode/geonode/issues/11424 to make the backport.
