### ISSUE TITLE
Problems running this project

### ISSUE THREAD

**Issue by Davide-sd** [GeoNode/geonode-project#5]
I'm having problems to run this project, both in my local machine and a freshly setup virtual machine, both running Ubuntu 16.04.

Docker version 1.13.0, build 49bf474
docker-compose version 1.10.0, build 4bd6f1a

Here are the steps to replicate the problem:

1. Open the terminal, run the command: `docker run -v 'pwd':/usr/src/app GeoNode/django:geonode django-admin.py startproject --template=https://github.com/GeoNode/geonode-project/archive/docker.zip -epy,rst,yml my_geonode`
2. Change my_geonode permission: sudo chown -R $USER:$USER my_geonode
3. `cd my_geonode`
4. `docker-compose up`

At this point the images are going to be retrieved, but an error rise when trying to pull waybarrios/geoserver:
> Pulling geoserver (waybarrios/geoserver:latest)...
> ERROR: manifest for waybarrios/geoserver:latest not found

So, I downloaded the necessary docker files from the [waybarrios/geoserver repo](https://github.com/waybarrios/geoserver-docker), these are the steps:
1. `cd /my-docker-images/`
2. `git clone https://github.com/waybarrios/docker-geoserver.git`
3. `cd docker-geoserver`
4. `docker build -t "waybarrios/geoserver" .`

At this point, I went back into *my_geonode* folder, and ran again the command `docker-compose up`. [This pastebin](http://pastebin.com/uRRJMYWB) shows everything that have been printed on the screen.

Following the instructions on this repom, I opened a new terminal and run this command:
`docker-compose run django python manage.py migrate`
but it exited with an error. You can see what has been printed on the screen in this [pastebin](http://pastebin.com/HEQ35T92).

Am I doing something wrong?

**Comment by waybarrios** [comment]
Hi @Davide-sd Please you have to use the last one geoserver image from master geonode.

You can see it on the following docker-compose https://github.com/GeoNode/geonode/blob/master/docker-compose.yml#L34

This geoserver image has oath2 authentication, so it is the last updated image

**Comment by anjogu** [comment]
Hey, 
I can't find the local_settings.py.sample file can anyone assist me in this?

**Comment by simod** [comment]
@anthony-njogu local_settings is obsolete. You can just tune the settings.py file.

best
