### ISSUE TITLE
README instructions always point to GN_VERSION=master

### ISSUE THREAD

**Issue by nicokant** [GeoNode/geonode-project#526]
The instructions on the README should be improved and should be clear that `GN_VERSION` is the actual branch of geonode-project you want to set up.

I noted that because I was setting up the project following the instructions from the branch `4.2.x` but I got installed the master branch

**Comment by giohappy** [comment]
Thanks @nicokant 
Done in https://github.com/GeoNode/geonode-project/commit/a09070e612d93c811497c2ede9793bf3edcbefc5
