### ISSUE TITLE
home page went blank after restoring geonode project

### ISSUE THREAD

**Issue by BinoyKadakkal** [GeoNode/geonode-project#529]
Version: Geonode project 4.1.3
Geoserver version: 2.23.3

I attempted to use the bash file included in the 'br' folder to restore the web portal hosted by Geonode Project from a domain with an SSL certificate (https://example.org) to my local system (http://localhost). All functions were functioning normally after the restoration, except the home page went blank.

![Screenshot from 2024-04-25 15-59-43](https://github.com/GeoNode/geonode-project/assets/108899419/2460829c-8f83-455c-843a-eb8b69fea9b8)

**Comment by giohappy** [comment]
@BinoyKadakkal this is a known problem with the b/r for projects.
It's been fixed in GeoNode 4.1.5

**Comment by giohappy** [comment]
@BinoyKadakkal this is a known problem with the b/r for projects.
It's been fixed in GeoNode 4.1.5

**Comment by BinoyKadakkal** [comment]
Is there another method to resolve the issue with version 4.1.3?

**Comment by giohappy** [comment]
If you want to apply the fix to your own GeoNode you will need to replicate the commit https://github.com/GeoNode/geonode/commit/99df666fdf32961ad9ccd3848583282ab0ae06d0

However, I suggest to upgrade to 4.1.5 rather then forking your own GeoNode

**Comment by BinoyKadakkal** [comment]
thank you
