### ISSUE TITLE
SELinux support

### ISSUE THREAD

**Issue by frafra** [GeoNode/geonode-project#53]
Celery cannot access to `/mnt/volumes/statics/geonode_init.lock` while using docker-compose up --build in a new project, so it keep restarting.

I removed a couple of fixtures to overcome issue #52

```
django4nina_catalog | **************************fixtures********************************
django4nina_catalog | Installed 1 object(s) from 1 fixture(s)
celery4nina_catalog | fixture task done
celery4nina_catalog | /bin/bash: /mnt/volumes/statics/geonode_init.lock: Permission denied
celery4nina_catalog | **************************init file********************************
django4nina_catalog | Installed 1 object(s) from 1 fixture(s)
django4nina_catalog | Installed 300 object(s) from 1 fixture(s)
django4nina_catalog | fixture task done
django4nina_catalog | /bin/bash: /mnt/volumes/statics/geonode_init.lock: Permission denied
django4nina_catalog | **************************init file********************************
celery4nina_catalog exited with code 1
```

Branch: 2.8

**Comment by frafra** [comment]
Reproducible on master.

**Comment by frafra** [comment]
It seems that this is related with SELinux. As Geonode supports CentOS, it would be nice to have a couple of additional commands for setting it in the README.md.

**Comment by afabiani** [comment]
@frafra would it be possible for you to send out the sequence of commands to add?

**Comment by frafra** [comment]
It seems that this is an issue related to that: https://danwalsh.livejournal.com/81269.html
I still need to find a proper solution.

**Comment by t-book** [comment]
@frafra Is this issue still open or can we close here (->2018) ?

**Comment by frafra** [comment]
@t-book I think it can be closed and reopened again if it still happens.
