### ISSUE TITLE
Problem in the option to update the metadata abstract field of a dataset in geonode version 4.2.4.

### ISSUE THREAD

**Issue by romelvazquez** [GeoNode/geonode-project#536]
Hello, I would like to know if the problem of changing the data in the Metadata Abstract field in a dataset has been solved. When I click edit metadata the summary field is not displayed in an editable text field in version 4.2.4. This issue is resolved in the stable demo version. 
Geonode 4.2.4
![image](https://github.com/GeoNode/geonode-project/assets/6538294/74cd8eb0-dd6e-471f-aa28-7c9c9d80cc91)
[Stable.](https://stable.demo.geonode.org/)
![image](https://github.com/GeoNode/geonode-project/assets/6538294/bfb2f919-a239-411a-bf8f-2a8453840ad7)

thanks,

**Comment by giohappy** [comment]
@romelvazquez this is unexpected. Stable is using 4.2.x, which is basically [aligned to 4.2.4](https://github.com/GeoNode/geonode/compare/4.2.4...4.2.x) , so they should behave the same on this side.

The problem you reported was affecting the master branch, because of a problematic upgrade of a javascript dependency (tinymce), but it has been[ fixed](https://github.com/GeoNode/geonode/commit/73055bde345622d4c12abb3ebc2e3eec7750d191) meanwhile.

Can you please double check the version of your instance? You can take a look at `/yourgeonode.com/version.txt`

**Comment by romelvazquez** [comment]
Hello Giovanni My versión is 4.4.0.dev0

See https://geo.geosfasplus.tech/versión.txt

**Comment by giohappy** [comment]
In that case it means you're using an outdated version of the master branch.
I invite you to test with the latest commit.

**Comment by kjetpett** [comment]
@giohappy I experience the same issue that @romelvazquez describes. 

I follow the basic Geonode Basic installation-tutorial (for docker):

After cloning the repo from https://github.com/GeoNode/geonode-project.git I run:
git checkout -b 4.2.x

Becore running docker compose build I altered the newly created .env file:
GEONODE_BASE_IMAGE_VERSION=4.2.x

When I try https://{my_server}/version.txt my version reports as:
4.4.0.dev0

Did I forget something?

**Comment by giohappy** [comment]
The reported version says that you're installing the master version. I don't understand why you get it. GeoNode project 4.2.x Docker images build [using GeoNode 4.2.x](https://github.com/GeoNode/geonode-project/blob/4.2.x/src/requirements.txt#L3).

Could you please test building it again with no-cache (`docker compose build --no-cache django celery`)?

**Comment by kjetpett** [comment]
I tried  `docker compose build --nocache` and that made no difference.

`docker compose build --no-cache django celery` was never able to finish.

**Comment by kjetpett** [comment]
The latest update (may 20th) now says: 4.2.5.dev0

Unfortunately I still can't edit Abstract. I removed containers, images, volumes and basically did the whole install procedure again.

**Comment by kjetpett** [comment]
@giohappy I can confirm that 4.3.x works! Thank you!
