### ISSUE TITLE
Can't add basemaps

### ISSUE THREAD

**Issue by whittaker007** [GeoNode/geonode-project#547]
I can add a new layer source, but clicking the basemap thumbnail does not provide the + button to add a new basemap the way Mapstore does. Is there some other place to add basemaps in GeoNode, or is this functionality missing? I don't see basemaps mentioned in the documentation.

**Comment by giohappy** [comment]
@whittaker007 I confirm the GeoNode client doesn't support adding baselayers from the baselayers selector. You can change / extend them with the [MAPSTORE_BASELAYERS settings](https://docs.geonode.org/en/master/basic/settings/index.html#mapstore-baselayers).

PS: Let's use the the geonode mailing-lists or gitter channel for questions.

**Comment by whittaker007** [comment]
Thanks, I have made a tiny bit of progress after spending a lot of time on this. I added a question to https://groups.google.com/a/opengeo.org/g/geonode-dev/c/w2ndMkFWs6w - is this the correct place to ask? Is there a more active place for discussion?
