### ISSUE TITLE
change name of site_index.html in (geonode-project/project_name/templates/site_index.html) to index.html

### ISSUE THREAD

**Issue by d3netxer** [GeoNode/geonode-project#56]
In production does site_index.html need to be names index.html? That is the only way I am seeing the changes showing up for me. 

If this is the case, let's change the name of site_index.html to index.html

**Comment by t-book** [comment]
I don´t think renaming is the way to go. urls is pointing correctly to site_index https://github.com/GeoNode/geonode-project/blob/master/project_name/urls.py#L33
further site_index is extending index. the question is why {% block hero %} is not taken into account anymore. I think it´s something here https://github.com/GeoNode/geonode/blob/master/geonode/templates/index.html#L13 Will try to have a look when the christmas tralala is over ;)

**Comment by t-book** [comment]
@d3netxer 
It´s the block.super in site_index if you remove it it´ll work.
See: https://github.com/t-book/geonode-project/commit/b1de1f152447e5d26df4138e703ad6aacdd18ca5

@afabiani  I don´t think we need  block.super here and would remove it. Do I miss something or is it okay to create a PR?

**Comment by afabiani** [comment]
@t-book can you send a PR accordingly? It works on my side but I'm not following the specific use case.

**Comment by t-book** [comment]
@afabiani let´s close this issue?

**Comment by francbartoli** [comment]
@t-book @afabiani Can I close this?

**Comment by t-book** [comment]
@francbartoli yes! thanks!
