### ISSUE TITLE
docker-compose up is broken

### ISSUE THREAD

**Issue by francbartoli** [GeoNode/geonode-project#58]
Containers of django and celery don't go up with the following error:

```
[uwsgi-cron] command "/usr/local/bin/python /usr/src/my_geonode/manage.py collect_metrics -n" running with pid 432 exited after 3 second(s)
Fri Dec 21 08:38:42 2018 - [uwsgi-cron] running "/usr/local/bin/python /usr/src/my_geonode/manage.py collect_metrics -n" (pid 440)
Unknown command: 'collect_metrics'
Type 'manage.py help' for usage.
```

Effectively running the command from the shell of the container gives the same error and the usage doesn't return the `collect_metrics` as available command

**Comment by afabiani** [comment]
That command should be available with "MONITORING=True"

**Comment by francbartoli** [comment]
@afabiani thanks, I see. Do you think it makes sense to override the whole snippet about monitoring? I'm wondering if it is already managed to establish the correct hostname in case of docker environment

**Comment by afabiani** [comment]
@francbartoli you mean disabled by default? Or expose more env variables?

**Comment by francbartoli** [comment]
At the moment it is declared from `uwsgi.ini` while monitoring is not enabled on settings when a fresh new brand geonode-project is created

**Comment by afabiani** [comment]
maybe let's comment this command on uwsgi and document how enabled it, as people would like to disable Monitoring.

**Comment by francbartoli** [comment]
Still not up after fixing #54. Still problem on `uwsgi` which is complaining with `invalid request block size: 21573 (max 4096)...skip`

**Comment by francbartoli** [comment]
This sort of error has been already reported https://github.com/jrief/django-websocket-redis/issues/27 for the communication between `nginx` and `uwsgi`. @afabiani do you have any idea if once the http socket changed then the configuration for nginx has been amended accordingly?

**Comment by afabiani** [comment]
Quite strange I tested the docker few days ago without problems.

Will double check again as soon as possible.

**Comment by francbartoli** [comment]
@afabiani I confirm what I thought:

Current geonode-project `uwsgi.ini` configuration:
```
[uwsgi]
socket = 0.0.0.0:8000
# http-socket = 0.0.0.0:8000
```

Geonode `uwsgi.ini` configuration:
```
[uwsgi]
uwsgi-socket = 0.0.0.0:8000
# http-socket = 0.0.0.0:8000
```

If we want to go with a socket (i.e. `socket = /tmp/uwsgi.socket`) as it is now this repo we have to share it as volume, mount that in the nginx container and change the conf directive to something like:
`proxy_pass http://unix:/path/to/uwsgi.socket;`

Otherwise I would use `http-socket = 0.0.0.0:8000` which is the only working for me as not even `uwsgi-socket` was good with the same error `502` from HTTP response and in the `geonode.log`:

`invalid request block size: 21573 (max 4096)...skip`

**Comment by francbartoli** [comment]
I have to rectify the last part of last comment:

`uwsgi-socket = 0.0.0.0:8000` works so I'd use this one as a patch. I'll send a PR for it.
