### ISSUE TITLE
Installation of requirements.txt shows incompatibility of oauthlib

### ISSUE THREAD

**Issue by francbartoli** [GeoNode/geonode-project#72]
During the step of the dockerfile:
`RUN pip install --upgrade --no-cache-dir --src /usr/src -r requirements.txt`

this message is appearing:
`requests-oauthlib 1.2.0 has requirement oauthlib>=3.0.0, but you'll have oauthlib 2.1.0 which is incompatible`

**Comment by amefad** [comment]
On the same step (using 2.8 branch) I get a few more messages:

ERROR: django-haystack 2.8.0 has requirement Django>=1.11, but you'll have django 1.8.19 which is incompatible.
ERROR: django-oauth-toolkit 0.12.0 has requirement oauthlib==2.0.1, but you'll have oauthlib 2.0.6 which is incompatible.
ERROR: pycsw 2.0.3 has requirement lxml==3.6.2, but you'll have lxml 3.8.0 which is incompatible.
ERROR: pycsw 2.0.3 has requirement OWSLib==0.10.3, but you'll have owslib 0.15.0 which is incompatible.
ERROR: pycsw 2.0.3 has requirement pyproj==1.9.3, but you'll have pyproj 1.9.5.1 which is incompatible.
ERROR: pycsw 2.0.3 has requirement Shapely==1.3.1, but you'll have shapely 1.5.17.post1 which is incompatible.
ERROR: requests-oauthlib 1.2.0 has requirement oauthlib>=3.0.0, but you'll have oauthlib 2.0.6 which is incompatible.
ERROR: flake8 2.5.4 has requirement pyflakes<1.1,>=0.8.1, but you'll have pyflakes 1.6.0 which is incompatible.
