### ISSUE TITLE
Dockerfile expression to get correct pygdal version fails

### ISSUE THREAD

**Issue by amefad** [GeoNode/geonode-project#82]
Using 2.8 branch docker-compose build fails when unable to correctly assign the $PYGDAL_VERSION variable The expression:

PYGDAL_VERSION="$(pip install pygdal==$GDAL_VERSION 2>&1 | grep -oP '(?<=: )(.*)(?=\))' | grep -oh $GDAL_VERSION\.[0-9])"

on line 38 returns 2 lines. 

Solution:
Append " | tail -1 " to the expression to return only one line.

**Comment by francbartoli** [comment]
Closed by https://github.com/GeoNode/geonode-project/commit/26236acbd6af4f487a714e4a96e0016c5b652d3e
