### ISSUE TITLE
"CommandError: No fixture named 'initial_data' found" during build

### ISSUE THREAD

**Issue by fpennica** [GeoNode/geonode-project#88]
Hello,
when building the image in a fresh new geonode-project with `docker-compose -f docker-compose.yml -f docker-compose.override.yml build --no-cache`:

```
...
django4igag_geonode | CommandError: No fixture named 'initial_data' found.
django4igag_geonode | ***************************initial*********************************
...
```

I tried changing in `tasks.py` the line:

`ctx.run("python manage.py loaddata /usr/src/geonode/geonode/base/fixtures/initial_data.json \`

in:

`ctx.run("python manage.py loaddata initial_data.json \` 

and it works, but I don't know if it's correct.

**Comment by fpennica** [comment]
I'm sorry, the error is not in the build process, but when executing:

`docker-compose -f docker-compose.yml -f docker-compose.override.yml up`

**Comment by rli-rms** [comment]
I got exactly the same error today:
![no fixuture](https://user-images.githubusercontent.com/45500815/61072182-9d09df00-a3c7-11e9-8c16-0ad84a089974.PNG)

**Comment by francbartoli** [comment]
Closed by https://github.com/GeoNode/geonode-project/commit/b25aba95d8966f757430a2ddd0c34d2e7698df00
