### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by dpadron** [GeoNode/geonode-project#93]
Good day

I am trying to install the Geonode 2.10 project follow these steps:

1.- git clone https://github.com/GeoNode/geonode-project.git

2.- mkvirtualenv my_geonode
pip install Django == 1.11.21

3.- django-admin startproject --template =. / Geonode-project -e py, rst, json, yml, ini, env, sample -n Dockerfile my_geonode

4.- cd my_geonode

5.- Edit wsgi.py to use local_setting.py
os.environ.setdefault ("DJANGO_SETTINGS_MODULE", "my_geonode.local_settings")

6.- Rename local_setting.py.sample> local_setting.py

7.- I edit docker-compose.override.ym and register my domain

8.- docker-compose build --no-cache

9.- docker-compose up to -d

Problem seeing django4_my_geonode records

Error: django.db.utils.OperationalError: could not connect to server: connection refused

Any ideas to solve this problem?

Thanks for your attention

![config_local_setting](https://user-images.githubusercontent.com/7094961/61785719-8c685880-ae0c-11e9-9639-e58a99a730b4.jpg)

![Connection_refused](https://user-images.githubusercontent.com/7094961/61785725-925e3980-ae0c-11e9-91b4-0f17075f11da.jpg)

**Comment by ppasq** [comment]
For support you should ask the list: geonode-users@lists.osgeo.org
However if your installation is based on Docker the database host is 'db' and not 'localhost' anymore. So you must edit your settings accordingly.
Closing this. For further support pls ask the list. Thanks.
