### ISSUE TITLE
 CreateLayer function

### ISSUE THREAD

**Issue by dpadron** [GeoNode/geonode-project#94]
Hi good day
Note that the crealayer function is not available in this version of geonode-project. Should we wait for an update? or can be activated

![image](https://user-images.githubusercontent.com/7094961/61998453-ade96e80-b0b0-11e9-8723-a7bd8b8ce324.png)

**Comment by t-book** [comment]
Hi @dpadron have you tried to add the following to your local_settings.py

# Settings for CREATE_LAYER plugin
```
CREATE_LAYER = True

if CREATE_LAYER:
    if 'geonode.geoserver.createlayer' not in INSTALLED_APPS:
        INSTALLED_APPS += ('geonode.geoserver.createlayer',)
```

Further, in case you have overwritten base.html within your project be sure that you have the following present:

https://github.com/GeoNode/geonode/blob/68ed462b202bf38ba06783661a13d274f8aea2a2/geonode/templates/base.html#L236-L238
