### ISSUE TITLE
Login failed in dev mode

### ISSUE THREAD

**Issue by rli-rms** [GeoNode/geonode-project#95]
## Expected Behavior
After building a new Geonode instance from scratch in development mode, use the admin credential  `admin` & `admin` to log in, the login should be successful.

Create some other accounts (either superuser or user) then try to log in with them. The logins should also be successful.

## Actual Behavior
1. `admin` account cannot be found, therefore login was failed.
![image](https://user-images.githubusercontent.com/45500815/62162740-bd91ce80-b2cd-11e9-9b31-2e72cd52343f.png)

![image](https://user-images.githubusercontent.com/45500815/62165598-ace45700-b2d3-11e9-84d8-37217410989b.png)

2. Using any other account to log in will be immediately kicked out by getting a `Session is Expired. Please login again!` message.
![image](https://user-images.githubusercontent.com/45500815/62160565-20cd3200-b2c9-11e9-8018-0b0212131aee.png)

## Steps to Reproduce the Problem

  1. git clone the current version of geonode-project files
  2. Run `docker-compose -f docker-compose.development.yml -f docker-compose.development.override.yml up --build` to build and run the geonode in dev mode
  3. Use admin credential to log in, this will fail.
  4. Create a new account either using `Register` or command line `django-admin createsuperuser` .
  5. Log in to Geonode with the account created in the above step, the account will log in first but will be logged out instantly. 

## Specifications

  - GeoNode version: 2.10rc5
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): GeoNode docker
  - Platform: Ubuntu 16.04 
  - Additional details:  Running `docker-compose -f docker-compose.yml -f docker-compose.override.yml up --build` to build and run the geonode won't encounter the issues. Only the dev mode has the problem described above.

**Comment by t-book** [comment]
ref.: https://github.com/GeoNode/geonode/issues/4719

**Comment by t-book** [comment]
@rli-rms see: https://github.com/GeoNode/geonode-project/issues/78

**Comment by neroznik** [comment]
After installing geonode via Docker, I have same problem. 
I am beginner in Geonode as well as in Linux.  
For installing geonode 2.10 I use manual from geonode web site.   [http://docs.geonode.org/en/2.10.x/install/core/index.html#docker](url)
Could you please describe how to solve it with more detail explanation. Thank you advance

**Comment by anjogu** [comment]
After setting up GeoNode 2.10.x in ubuntu 18.04.3 and running it in development mode, I created an admin user with admin as the password. After using these credentials to log in the session Expires immediately as shown below. Does anyone know how can I solve this?
![sessionExpired](https://user-images.githubusercontent.com/30499063/75007664-e1de1400-5486-11ea-94ed-dc7295ee70dd.png)

**Comment by t-book** [comment]
@anjogu most likely your paver sync did not finish successfully and did not install the fixture for oauth2. try to repeat this step and double-check your oauth2 config on both sides (geonode && geoserver)

**Comment by anjogu** [comment]
@t-book I am using apache and not paver

**Comment by anjogu** [comment]
@t-book Thank you it worked

**Comment by iamtekson** [comment]
I am using the latest version of geonode from the master branch. I am facing the same issue. I already tried following command, 

```bash
DJANGO_SETTINGS_MODULE=geonode.local_settings paver reset
DJANGO_SETTINGS_MODULE=geonode.local_settings paver setup
DJANGO_SETTINGS_MODULE=geonode.local_settings paver sync
DJANGO_SETTINGS_MODULE=geonode.local_settings python manage.py collectstatic --noinput
```

```bash
sudo PYTHONWARNINGS=ignore VIRTUAL_ENV=$VIRTUAL_ENV DJANGO_SETTINGS_MODULE=geonode.local_settings GEONODE_ETC=/opt/geonode/geonode GEOSERVER_DATA_DIR=/opt/data/geoserver_data TOMCAT_SERVICE="service tomcat9" APACHE_SERVICE="service nginx" geonode_updateip -p localhost
```
But didn't resolve. Can you help me @t-book please?

**Comment by iamtekson** [comment]
PS: I tried to restore the old geonode using this command

```bash
python manage.py restore --backup-file=2021-02-04-3245.zip --config=2021-02-04-244324.ini --settings=geonode.local_settings
```
I am also unable to restore. It shows the error message as 

```
There are 0 layers which could not be updated because of errors
HINT: If you migrated from another site, don't forget to run the command 'migrate_baseurl' to fix links
```

**Comment by iamtekson** [comment]
> @anjogu most likely your paver sync did not finish successfully and did not install the fixture for oauth2. try to repeat this step and double-check your oauth2 config on both sides (geonode && geoserver)

How to check the oauth2 config on both sides (geonode && geoserver)

**Comment by iamtekson** [comment]
I just solve the issue by `paver reset_hard`. And follow the suggestion as mentioned above `paver sync`. Thank you
